import HeaderComponent from "@/components/Header";
import { MainComponent } from "@/components/Main";

import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      
        {/* <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css" /> */}
      </Head>
      <main>
        
          <HeaderComponent/>
          <MainComponent/>
          

    
      
      </main>
    </>
  );
}
